### PR TITLE
Adjust top left relay logo to the new style

### PR DESCRIPTION
**Pull request by BrianS111**
PR for https://github.com/relaycc/relay/issues/77

The logo in the top right will now say Relay also.

### CODE REVIEW

**Comment by BrianS111** [comment]
Here is the new logo on all screen sizes

Image 1-6-23 at 11 43 AM
Image 1-6-23 at 11 45 AM
Image 1-6-23 at 11 45 AM (1)
Image 1-6-23 at 11 46 AM

**Comment by BrianS111** [comment]
The alignment / size looks slightly off in the two middle shots. I'm gonna do a bit of tweaking.

**Comment by BrianS111** [comment]
Let me know if this looks good, or if anyone has alignment / size recommendations beyond these

https://user-images.githubusercontent.com/81312527/211091167-59b145cb-70e0-4f9f-a2c9-db0d874a71c9.mov

**Comment by killthebuddh4** [comment]
@oswidandesign @BrianS111 Is there something wrong with the image file? It looks _super rough_ to me.
image

**Comment by seanrelay** [comment]
Screen Shot 2023-01-10 at 12 36 16 PM
 mine is good

**Pull request closed without merging**
