### PR TITLE
Updating the cards with current data from google docs as of 12/12

### PR DESCRIPTION
**Pull request by BrianS111**
Closes https://github.com/relaycc/relay/issues/65

### CODE REVIEW

**Comment by BrianS111** [comment]
The new cards have been added. Also data for all of the descriptions have been added. The descriptions aren't displayed on the card yet as that is a separate issue that I will get to
https://user-images.githubusercontent.com/81312527/207182297-418045cc-9040-4a10-9472-8bdba1d79d54.mov

**Comment by killthebuddh4** [comment]
@seanrelay @andrewvdp There isn't really any code changes with this one, please check out the preview deployment and approve if it LGTY.

**Review by oswidandesign — COMMENTED** [review]
interep
Are these supposed to be 400x400 (most of them are here) or 128x128 (size on relay.cc)? 
I went through all the logos and adjusted all to 400x400, and made backgrounds white fopr transparent logos-- only one I couldn't find was GovernorBeta logo. I have attached all files that should be updated: 
0x
aave
alchemymixfi
apecoindao
aragon
audis
bitdao
butterfly
collabland
colony
dxdao
emaphore
ethermail
interep

**Review by seanrelay — APPROVED** [review]
lgtm

**Comment by seanrelay** [comment]
> interep Are these supposed to be 400x400 (most of them are here) or 128x128 (size on relay.cc)? I went through all the logos and adjusted all to 400x400, and made backgrounds white fopr transparent logos-- only one I couldn't find was GovernorBeta logo. I have attached all files that should be updated: 0x aave alchemymixfi apecoindao aragon audis bitdao butterfly collabland colony dxdao emaphore ethermail interep

@oswidandesign @killthebuddh4 can you comment on how resizing images works? because I think these will always be in a small format, compared to how they look in this comment.

**Comment by killthebuddh4** [comment]
>  @oswidandesign @killthebuddh4 can you comment on how resizing images works? because I think these will always be in a small format, compared to how they look in this comment.

Next.js (and Vercel) do a lot behind the scenes to generate, serve, and cache images at optimal sizes. Ideally all of the logos would be the default size (128x128) and the same format, and we'd have some sort of basic pipeline or process for normalizing the images, but it probably won't matter any time soon.

There might be another reason that I'm not aware of to use 400x400 images on the backend. I'm pretty sure that most of the images in our repo are all different sizes right now. Does that help answer your question @seanrelay ?

**Comment by killthebuddh4** [comment]
@BrianS111 Can you confirm that this PR is now unnecessary?

**Comment by killthebuddh4** [comment]
Closing because duped.

**Pull request closed without merging**
