### PR TITLE
Feature/social landing page links

### PR DESCRIPTION
**Pull request by BrianS111**
Draft PR for https://github.com/relaycc/relay/issues/19

### CODE REVIEW

**Comment by killthebuddh4** [comment]
> Draft PR for #19

Is this PR for #18 or #19?

**Comment by BrianS111** [comment]
closes https://github.com/relaycc/relay/issues/18

**Review by killthebuddh4 — CHANGES_REQUESTED** [review]
* There's 2 NavBar components, the changes in NavBarConversations need to go in the other one as well.
* Please remove any of the files in /public that aren't being imported anywhere (it looks like this might be all of them)

**Comment by killthebuddh4** [comment]
@BrianS111 It looks like this branch is different than the video [here](https://github.com/relaycc/relay/issues/18#issuecomment-1267613027). Here's a screenshot from the current deployed branch
image

**Comment by killthebuddh4** [comment]
It might be because of the version thing I mentioned above, but just wanted to mention that the social icons in the preview deployment don't seem to be working.

**Comment by BrianS111** [comment]
https://user-images.githubusercontent.com/81312527/193950257-16759aa2-3911-467a-8e41-14bc3ef8519c.mov

Here is the latest version I pushed with the search bar on top

**Comment by BrianS111** [comment]
https://user-images.githubusercontent.com/81312527/193950817-d3ec2f3b-4a6c-4225-8814-cbc2636e3c3d.mov

I posted an old video a second ago. Here is the correct one with the search bar on top and current version

**Comment by BrianS111** [comment]
Closes #18

**Comment by BrianS111** [comment]
> It might be because of the version thing I mentioned above, but just wanted to mention that the social icons in the preview deployment don't seem to be working.

They are working when I view the deployment, locally, and if you look in the code they are there

**Comment by BrianS111** [comment]
> * There's 2 NavBar components, the changes in NavBarConversations need to go in the other one as well.
> * Please remove any of the files in /public that aren't being imported anywhere (it looks like this might be all of them)

They are in both components. I'll work on removing any unused files in public

**Comment by BrianS111** [comment]
https://user-images.githubusercontent.com/81312527/194124458-d9ccd1dd-b520-4e8f-aabe-ac107a33e2ca.mov

Here is the current version. Unused icons in the public directory have been removed. This PR should be ready to be merged

**Review by killthebuddh4 — APPROVED** [review]

**Pull request merged**
