### PR TITLE
Added Otterspace card

### PR DESCRIPTION
**Pull request by BrianS111**
Closes https://github.com/relaycc/relay/issues/14

https://user-images.githubusercontent.com/81312527/194438167-4ffed899-47bc-414c-8a60-636b8ef7fc27.mov

### CODE REVIEW

**Review by killthebuddh4 — CHANGES_REQUESTED** [review]
If you look closely in the video you posted you'll see that on hover the logo is overflowing the container. It's more noticeable in the preview deployment:

image

The AppCard takes a `logoClassName` prop you can probably use to fix this.

**Review by killthebuddh4 — CHANGES_REQUESTED** [review]
I'd prefer not to add styling to the underlying `Card` component to fix this is issue with one instance of one type of card. Instead, let's just remove the `pl-4` from the `Header > h1` element. This isn't a great solution either because it will break as soon as we have a title with a single 11 or 12 character word, but it is more precise.

**Comment by BrianS111** [comment]
0C1905AA-7AAA-4D6E-9620-620D4715AFBD
Even with the current setup... boardroom overflows also. I don't think we should ever have things overflowing off cards. Also, Re: padding... I think we should take it off all the headers to fix alignment. 1 sec video coming soon

**Comment by killthebuddh4** [comment]
@BrianS111 Can you push the code corresponding to the video you just shared.

**Comment by BrianS111** [comment]
@killthebuddh4 Pushed

**Comment by BrianS111** [comment]
Any update on if any more adjustments need to be made here? Only asking because it's marked as a P1 and appears to have become stale

**Comment by killthebuddh4** [comment]
> 

`overflow-hidden` still needs to be removed from the `Card` element

**Review by killthebuddh4 — APPROVED** [review]

**Pull request merged**
