### PR TITLE
Typing in the URL can link to the specific section

### PR DESCRIPTION
**Pull request by BrianS111**
https://github.com/relaycc/relay/issues/85

The user will be able to get to the music section by typing relay.cc/music etc..

### CODE REVIEW

**Comment by BrianS111** [comment]
I don't think this is the approach you want me to take @killthebuddh4 ... but this is what I came up with for the shallow routing '/?category=music',  setup. I couldn't do it without setting up new pages and running into a 404 error when someone searches relay.cc/music. so I have all the pages pointing at the main page, where the shallow routing kicks in. 

The main problem here is there is a short delay when the user enters in relaycc/music and is directed to the main page. The quick thing I did was just put the same background there. 

Let me know if this is at least in the right direction or if we are attempting to go with a completely different setup.

**Comment by seanrelay** [comment]
Screenshot 2023-01-15 at 10 10 52 PM
@BrianS111 deployment failure with this error

**Comment by BrianS111** [comment]
We good now, small typo

**Comment by BrianS111** [comment]
https://relay-git-directory-url-link-to-sections-relaycc.vercel.app

so now if you start with this URL and put /music or whatever section it should go to that section

**Comment by BrianS111** [comment]
Typing in a specific URL in the beginning is actually going way faster in this preview deployment than in my dev environment where there was a second or so delay of a blank screen before the first page load

**Comment by seanrelay** [comment]
Gotcha. So the music URL is:
https://relay-mhyouhg77-relaycc.vercel.app/?category=music 
and 
https://relay-mhyouhg77-relaycc.vercel.app/music redirects to that

**Comment by BrianS111** [comment]
> Gotcha. So the music URL is: https://relay-mhyouhg77-relaycc.vercel.app/?category=music and https://relay-mhyouhg77-relaycc.vercel.app/music redirects to that.
> 
> That's the functionality I want, where relay.cc/venture is the link people share. I commented in the issue why I think it's important to have a short link to share instead of /?category=venture I think that having a top-level route redirect like that could be considered technical debt as it's a nonstandard way to do it, as it blocks us from using the section names for something else.

Yeah that is the link they would share. relay.cc/venture and it would take them to the venture section. People don't need to type in the category part. only relay.cc followed by whatever category

**Comment by BrianS111** [comment]
> Gotcha. So the music URL is: https://relay-mhyouhg77-relaycc.vercel.app/?category=music and https://relay-mhyouhg77-relaycc.vercel.app/music redirects to that.
> 
> That's the functionality I want, where relay.cc/venture is the link people share. I commented in the issue why I think it's important to have a short link to share instead of /?category=venture I think that having a top-level route redirect like that could be considered technical debt as it's a nonstandard way to do it, as it blocks us from using the section names for something else.

So testing this as how it would work when deployed, delete the ?category stuff and put /(your category)

**Comment by killthebuddh4** [comment]
* @BrianS111 I think the way we want to do this is with [rewrites](https://nextjs.org/docs/api-reference/next.config.js/rewrites).
* We probably want to rewrite to `/search`. For example, see https://github.com/seach and https://twitter.com/explore
* So we would have 2 pages, `pages/index.tsx` and `/search.tsx`
* In the rewrites config we would rewrite `/music` to `/search?category=music`. We would do this with the rest of the categories as well
* We would also include a rewrite rule from `/` to `/search` so that people can navigate to `relay.cc` and not have to navigate to `relay.cc/search`

@BrianS111 Feel free to ping me in Discord if you have any questions.

**Comment by BrianS111** [comment]
> * @BrianS111 I think the way we want to do this is with [rewrites](https://nextjs.org/docs/api-reference/next.config.js/rewrites).
> * We probably want to rewrite to `/search`. For example, see https://github.com/seach and https://twitter.com/explore
> * So we would have 2 pages, `/pages/index.tsx` and `/pages/search.tsx`
> * In the rewrites config we would rewrite `/music` to `/search?category=music`. We would do this with the rest of the categories as well
> * We would also include a rewrite rule from `/` to `/search` so that people can navigate to `relay.cc` and not have to navigate to `relay.cc/search`
> 
> @BrianS111 Feel free to ping me in Discord if you have any questions.

Cool. I'll work on the changes en la mañana

**Comment by killthebuddh4** [comment]
Closed by  commit 09ad0256f49f7a3eb1e53ce9bbd013759ebf3a97

**Pull request closed without merging**
