### PR TITLE
Feature/social landing page links

### PR DESCRIPTION
**Pull request by BrianS111**
Temporarily removing search bar and adding social links in SVG format

### CODE REVIEW

**Comment by BrianS111** [comment]
https://github.com/relaycc/relay/issues/18

**Comment by killthebuddh4** [comment]
> #18

I think if you don't use `Closes #X` then the issue won't be closed when the PR is closed.

**Comment by andrewvdp** [comment]
> > #18
> 
> I think if you don't use `Closes #X` then the issue won't be closed when the PR is closed.

Can/Should we make this required when creating a PR?

**Comment by killthebuddh4** [comment]
> > > #18
> > 
> > 
> > I think if you don't use `Closes #X` then the issue won't be closed when the PR is closed.
> 
> Can/Should we make this required when creating a PR?

I don't think it should be automated, but the PR template has a section on linking issues. We need to update the PR template, add CONTRIBUTING.md, and issue templates, and maybe a few other housekeeping tasks. There's an issue open for this in at least one repo, I've been in my head planning on doing it all at once.

**Pull request closed without merging**
