### PR TITLE
Add a description view on app cards

### PR DESCRIPTION
**Pull request by BrianS111**
Closes https://github.com/relaycc/relay/issues/64

### CODE REVIEW

**Comment by BrianS111** [comment]
What do you guys think design wise? this is what I came up with for now. Let me know what direction we want to go in for displaying the description

https://user-images.githubusercontent.com/81312527/208328218-66e8717b-22a9-4479-a239-814a1ea193a5.mp4

**Comment by killthebuddh4** [comment]
@BrianS111 This is great, push the code and let's ship it.

**Comment by seanrelay** [comment]
> What do you guys think design wise? this is what I came up with for now. Let me know what direction we want to go in for displaying the description
> 
>  Relay.-.Personal.-.Microsoft.Edge.2022-12-18.16-39-40.mp4

Agree this looks shippable!

**Comment by killthebuddh4** [comment]
Closing because duped.

**Pull request closed without merging**
