### PR TITLE
Home page update

### PR DESCRIPTION
**Pull request by BrianS111**
Closes https://github.com/relaycc/relay/issues/51

### CODE REVIEW

**Comment by BrianS111** [comment]
@seanwbren @andrewvdp Do we have an updated link to 'Careers'? It looks like the current one is either broken or has nothing on it

**Comment by BrianS111** [comment]
Something we can do design wise now that we have the social icons in the footer, is in the top right corner of the page we can have a logo that says "(our logo) Relay profiles" or something along those lines instead of the social Icons there. Also maybe also a header somewhere towards the top to show the name of the profile you are on also. @seanwbren @vdp.eth


https://user-images.githubusercontent.com/81312527/204153847-a7e8008b-f009-45dd-822c-a8faba3a9c29.mov

**Comment by BrianS111** [comment]
Top left corner*

**Comment by seanrelay** [comment]
@BrianS111 yea that space can instead have the relay logo (which is a link to relay.cc ) and other things TBD.

**Comment by killthebuddh4** [comment]
Current Spec:

* Card looks like this
image

But with a couple minor changes
* Convert the "Open App"  button to a narrow button on the right that only has the icon
* To the left of the "Open App" button put a button that says "Message" and has the send message icon to the right of it

* Also includes the additional cards and tabs from the video that @BrianS111 posted above

**Comment by bribren7** [comment]
Posting my idea for how the cards views should work. There should be 2 different views.

**1st view:** Small icons with project icon and project name. Hover state opens that project's larger card. Approx. 50-100 on a page at a time.  Sorted by category.
image

**2nd view:** Medium size cards with project icon, project name, project description, send message, and a link out to their site. Approx. 6-18 on a page at a time. Sorted by category, order within category determined by popularity. 
As seen here: https://deepdao.io/dao_tools

**Comment by seanrelay** [comment]
@BrianS111 for the text for this:

instead of "user not on the network" it says "This app has not yet connected their ENS name or Lens handle to Relay"

And instead of "this user..." it says "Please message us if you are on this team, or share relay.cc with them!" 
and in that, "message us" is a blue link to the DM with connect.relaycc.eth

**Comment by BrianS111** [comment]
> @BrianS111 for the text for this:
> 
> instead of "user not on the network" it says "This app has not yet connected their ENS name or Lens handle to Relay"
> 
> And instead of "this user..." it says "Please message us if you are on this team, or share relay.cc with them!" and in that, "message us" is a blue link to the DM with connect.relaycc.eth

Changing that text would be in the receiver repo, possible though

**Comment by seanrelay** [comment]
> 

True. For @killthebuddh4.
or I feel anyone should be able to make a ticket for tracking inter-repo issues like this

**Comment by seanrelay** [comment]
relevant discussion: 
Screen Shot 2022-11-30 at 1 56 01 PM
Screen Shot 2022-11-30 at 1 56 20 PM

**Comment by BrianS111** [comment]
Everything is done so far except getting receiver to work dynamically with the cards that have an account to message, which I'm working on now

**Comment by killthebuddh4** [comment]
> Everything is done so far except getting receiver to work dynamically with the cards that have an account to message, which I'm working on now

Awesome! Make sure to commit your code here in case the Receiver update goes sideways (maybe just fallback to graying the buttons?). That way we could merge this PR and then get after the receiver changes separately.

**Comment by BrianS111** [comment]
K, I made a commit and pushed code for where I'm at now

**Comment by BrianS111** [comment]
@killthebuddh4 @seanrelay  Here is a video of what the site looks like now. When accounts have lens names. The thing is, The only section that has accounts signed up with lens names havent registered for xmtp, all the other sections don't have accounts so receiver pulls up this 'invalid' view for like 85% of our cards

https://user-images.githubusercontent.com/81312527/204898878-3678e809-fe02-4331-9c16-40c74dcf2971.mov

**Comment by seanrelay** [comment]
> @BrianS111 for the text for this:
> 
> instead of "user not on the network" it says "This app has not yet connected their ENS name or Lens handle to Relay"
> 
> And instead of "this user..." it says "Please message us if you are on this team, or share relay.cc with them!" and in that, "message us" is a blue link to the DM with connect.relaycc.eth

@BrianS111 regarding my text changes and what you said, I think @killthebuddh4 will change receiver to recognize that invalid error as something else

**Comment by BrianS111** [comment]
Ok, yeah those would be receiver updates. I think I have a PR open for text changes but it might be outdated now. 

Also now that we dont have a profile section, Do we still want the searchbar functionality, so when I type in "Seanwbren.eth"

The title of the ENS card says SeanWbren.eth, and the title of the lens card says your username? and the open chat buttons will open a receiver window to you? That's the only functionality I can think of the searchbar being useful for until we bring back profiles
 
7E3E623C-07BD-4796-B61A-DE09861541FC


@killthebuddh4 @seanwbren

**Comment by seanrelay** [comment]
Ok for the searchbar, @BrianS111 can you make it start a receiver chat with the address entered? cc: @killthebuddh4 

Profiles revamp to make it more like light.so style will be soon but for this moment they can be "commented out".

**Comment by killthebuddh4** [comment]
@BrianS111 Look into this please.
image

I also pulled the code and get the same build error locally too:

image

**Comment by BrianS111** [comment]
Oh wow, it didn't even show an error in the editor until I clicked the file. Ill fix it now

**Comment by killthebuddh4** [comment]
> Oh wow, it didn't even show an error in the editor until I clicked the file. Ill fix it now

We should probably have some sort of commit hook or GH action that automatically informs us of these kinds of problems. Until then my suggestion would be to run `npm run lint && npm run build` before pushing changes.

**Comment by BrianS111** [comment]
We aren't using that component anymore.. but I'm not sure if it's temporary or not once we integrate profiles again, so I commented out the code and returned a fragment incase we want to get back to using it, and we can adjust it at that time based on our needs. Seems like the way to go for now, I can also delete the file if we don't think we are going to go back to using it

**Comment by killthebuddh4** [comment]
@BrianS111 Can you run `npm run build` and post the output here. Something weird seems to be going on with Vercel. The build still fails locally for me.

**Comment by killthebuddh4** [comment]
> 

Nevermind @BrianS111 it was definitely my local environment!

**Comment by killthebuddh4** [comment]
@BrianS111 @seanrelay
image

**Comment by seanrelay** [comment]
Sweet, some image comments nothing blocking release soon, @brianjbren you can help?
Popular: ENS not showing, 101, Disco images are white when they should be black. 
Lens: the yup image isn't loading. 
 the lens image is supposed to be more like
 https://mirror.xyz/lensprotocol.eth/WrYEeoxijZDiqLezKVmN8YdmSXgWPRyyICJzP3Nk3Ek 
Music: remove first Audius card, the second one has a better image

**Comment by seanrelay** [comment]
Screen Shot 2022-11-30 at 5 30 23 PM

Remove the loading animation for cards, as they aren't connected to the xmtp conversation loading.

**Comment by BrianS111** [comment]
3DB71AE8-274A-4471-B8E9-84834EA43654
Do you want all the lens ones to look like this with the green background @seanrelay ?

**Comment by seanrelay** [comment]
ENS logo working + remove loading animation of cards are the changes to make for release.

Then adding latest Receiver code makes it good to deploy.

**Comment by BrianS111** [comment]
I already pushed the updated ENS and Yup icon. I didn't have the casing right but now it should be fixed

**Comment by BrianS111** [comment]
> ENS logo working + remove loading animation of cards are the changes to make for release.
> 
> Then adding latest Receiver code makes it good to deploy.

All of these have been completed except 'latest receiver code' By that do you mean the latest version of receiver? @killthebuddh4 was telling me to use 0.1.68 instead of 0.1.7

**Comment by seanrelay** [comment]
@BrianS111 looks good then, don't worry about the receiver version for this PR

**Comment by seanrelay** [comment]
And yes that Lens logo for all those is good

**Comment by killthebuddh4** [comment]
I'm working on bumping the receiver version.

**Comment by killthebuddh4** [comment]
@seanrelay Is connect.relaycc.eth set up already?
image

**Pull request merged**
