### PR TITLE
When you navigate to a profile, the page title should show their handle.

### PR DESCRIPTION
**Pull request by BrianS111**
Closes https://github.com/relaycc/relay/issues/2

### CODE REVIEW

**Comment by BrianS111** [comment]
https://user-images.githubusercontent.com/81312527/197074367-b2bccd05-fb3f-4b12-b7d2-85d5731f8916.mov

Ready to be merged

**Comment by killthebuddh4** [comment]
@BrianS111 I think this is not quite complete. See [this comment](https://github.com/relaycc/relay/issues/2#issuecomment-1271977822).

**Review by killthebuddh4 — CHANGES_REQUESTED** [review]
See https://github.com/relaycc/relay/pull/47#issuecomment-1286274074

**Comment by BrianS111** [comment]
https://user-images.githubusercontent.com/81312527/197088978-4c5cbc7f-2898-41f3-b01b-db2aed5eb6dc.mov

Alright, we are good now.

**Comment by BrianS111** [comment]
My bad, I misinterpreted the orig issue, but we should be good now.

**Pull request merged**
